import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import vendorsRouter from "./vendors";
import eventsRouter from "./events";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import availabilityRouter from "./availability";
import adminRouter from "./admin";
import contactRouter from "./contact";
import vendorRequestsRouter from "./vendorRequests";
import subscriptionsRouter from "./subscriptions";
import couponsRouter from "./coupons";
import partnerMediaRouter from "./partnerMedia";
import blockedDatesRouter from "./blockedDates";
import adsRouter from "./ads";
import referralsRouter from "./referrals";
import notificationsRouter from "./notifications";
import blogsRouter from "./blogs";
import adminBlogsRouter from "./adminBlogs";
import wishlistRouter from "./wishlist";
import aiChatRouter from "./aiChat";
import announcementsRouter from "./announcements";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(vendorsRouter);
router.use(eventsRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(availabilityRouter);
router.use(adminRouter);
router.use(contactRouter);
router.use(vendorRequestsRouter);
router.use(subscriptionsRouter);
router.use(couponsRouter);
router.use(partnerMediaRouter);
router.use(blockedDatesRouter);
router.use(adsRouter);
router.use(referralsRouter);
router.use(notificationsRouter);
router.use(blogsRouter);
router.use(adminBlogsRouter);
router.use(wishlistRouter);
router.use(aiChatRouter);
router.use(announcementsRouter);

export default router;
