import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import vendorsRouter from "./vendors";
import eventsRouter from "./events";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import availabilityRouter from "./availability";
import adminRouter from "./admin";
import contactRouter from "./contact";
import vendorRequestsRouter from "./vendorRequests";
import subscriptionsRouter from "./subscriptions";
import couponsRouter from "./coupons";
import vendorOffersRouter from "./vendorOffers";
import partnerMediaRouter from "./partnerMedia";
import partnerBankingRouter from "./partnerBanking";
import blockedDatesRouter from "./blockedDates";
import adsRouter from "./ads";
import referralsRouter from "./referrals";
import notificationsRouter from "./notifications";
import blogsRouter from "./blogs";
import adminBlogsRouter from "./adminBlogs";
import wishlistRouter from "./wishlist";
import announcementsRouter from "./announcements";
import storageRouter from "./storage";
import paymentsRouter from "./payments";
import managersRouter from "./managers";
import placesRouter from "./places";
import webPushRouter from "./webPush";
import seoRouter from "./seo";
import emailsRouter from "./emails";
import organizersRouter from "./organizers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(vendorsRouter);
router.use(eventsRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(availabilityRouter);
router.use(adminRouter);
router.use(contactRouter);
router.use(vendorRequestsRouter);
router.use(subscriptionsRouter);
router.use(couponsRouter);
router.use(vendorOffersRouter);
router.use(partnerMediaRouter);
router.use(partnerBankingRouter);
router.use(blockedDatesRouter);
router.use(adsRouter);
router.use(referralsRouter);
router.use(notificationsRouter);
router.use(blogsRouter);
router.use(adminBlogsRouter);
router.use(wishlistRouter);
router.use(announcementsRouter);
router.use(storageRouter);
router.use(paymentsRouter);
router.use(managersRouter);
router.use(placesRouter);
router.use(webPushRouter);
router.use(seoRouter);
router.use(emailsRouter);
router.use(organizersRouter);

export default router;
